// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/fileOperate.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CopyFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *CopyFileReq) Reset() {
	*x = CopyFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fileOperate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileReq) ProtoMessage() {}

func (x *CopyFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileOperate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileReq.ProtoReflect.Descriptor instead.
func (*CopyFileReq) Descriptor() ([]byte, []int) {
	return file_proto_fileOperate_proto_rawDescGZIP(), []int{0}
}

func (x *CopyFileReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyFileReq) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type MoveFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *MoveFileReq) Reset() {
	*x = MoveFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fileOperate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileReq) ProtoMessage() {}

func (x *MoveFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileOperate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileReq.ProtoReflect.Descriptor instead.
func (*MoveFileReq) Descriptor() ([]byte, []int) {
	return file_proto_fileOperate_proto_rawDescGZIP(), []int{1}
}

func (x *MoveFileReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MoveFileReq) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type DeleteFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fileOperate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileOperate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_proto_fileOperate_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RenameFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *RenameFileReq) Reset() {
	*x = RenameFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fileOperate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileReq) ProtoMessage() {}

func (x *RenameFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileOperate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileReq.ProtoReflect.Descriptor instead.
func (*RenameFileReq) Descriptor() ([]byte, []int) {
	return file_proto_fileOperate_proto_rawDescGZIP(), []int{3}
}

func (x *RenameFileReq) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RenameFileReq) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type FileOptRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *FileOptRep) Reset() {
	*x = FileOptRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fileOperate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileOptRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptRep) ProtoMessage() {}

func (x *FileOptRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileOperate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptRep.ProtoReflect.Descriptor instead.
func (*FileOptRep) Descriptor() ([]byte, []int) {
	return file_proto_fileOperate_proto_rawDescGZIP(), []int{4}
}

func (x *FileOptRep) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_fileOperate_proto protoreflect.FileDescriptor

var file_proto_fileOperate_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x70,
	0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x0b,
	0x4d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22,
	0x23, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x33, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xb9, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x12, 0x27, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0c, 0x2e,
	0x43, 0x6f, 0x70, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x08, 0x4d, 0x6f,
	0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0c, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x0e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x70, 0x22, 0x00,
	0x12, 0x2b, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e,
	0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fileOperate_proto_rawDescOnce sync.Once
	file_proto_fileOperate_proto_rawDescData = file_proto_fileOperate_proto_rawDesc
)

func file_proto_fileOperate_proto_rawDescGZIP() []byte {
	file_proto_fileOperate_proto_rawDescOnce.Do(func() {
		file_proto_fileOperate_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fileOperate_proto_rawDescData)
	})
	return file_proto_fileOperate_proto_rawDescData
}

var file_proto_fileOperate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_fileOperate_proto_goTypes = []interface{}{
	(*CopyFileReq)(nil),   // 0: CopyFileReq
	(*MoveFileReq)(nil),   // 1: MoveFileReq
	(*DeleteFileReq)(nil), // 2: DeleteFileReq
	(*RenameFileReq)(nil), // 3: RenameFileReq
	(*FileOptRep)(nil),    // 4: FileOptRep
}
var file_proto_fileOperate_proto_depIdxs = []int32{
	0, // 0: FileOperate.CopyFile:input_type -> CopyFileReq
	1, // 1: FileOperate.MoveFile:input_type -> MoveFileReq
	2, // 2: FileOperate.DeleteFile:input_type -> DeleteFileReq
	3, // 3: FileOperate.RenameFile:input_type -> RenameFileReq
	4, // 4: FileOperate.CopyFile:output_type -> FileOptRep
	4, // 5: FileOperate.MoveFile:output_type -> FileOptRep
	4, // 6: FileOperate.DeleteFile:output_type -> FileOptRep
	4, // 7: FileOperate.RenameFile:output_type -> FileOptRep
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fileOperate_proto_init() }
func file_proto_fileOperate_proto_init() {
	if File_proto_fileOperate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fileOperate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fileOperate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fileOperate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fileOperate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fileOperate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileOptRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fileOperate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fileOperate_proto_goTypes,
		DependencyIndexes: file_proto_fileOperate_proto_depIdxs,
		MessageInfos:      file_proto_fileOperate_proto_msgTypes,
	}.Build()
	File_proto_fileOperate_proto = out.File
	file_proto_fileOperate_proto_rawDesc = nil
	file_proto_fileOperate_proto_goTypes = nil
	file_proto_fileOperate_proto_depIdxs = nil
}
