// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/fileInfo.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileInfoClient is the client API for FileInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileInfoClient interface {
	GetFileInfo(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*RegularFileInfo, error)
	GetDirFileInfo(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*DirFileInfoList, error)
}

type fileInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewFileInfoClient(cc grpc.ClientConnInterface) FileInfoClient {
	return &fileInfoClient{cc}
}

func (c *fileInfoClient) GetFileInfo(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*RegularFileInfo, error) {
	out := new(RegularFileInfo)
	err := c.cc.Invoke(ctx, "/FileInfo/GetFileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileInfoClient) GetDirFileInfo(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*DirFileInfoList, error) {
	out := new(DirFileInfoList)
	err := c.cc.Invoke(ctx, "/FileInfo/GetDirFileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileInfoServer is the server API for FileInfo service.
// All implementations must embed UnimplementedFileInfoServer
// for forward compatibility
type FileInfoServer interface {
	GetFileInfo(context.Context, *FileReq) (*RegularFileInfo, error)
	GetDirFileInfo(context.Context, *FileReq) (*DirFileInfoList, error)
	mustEmbedUnimplementedFileInfoServer()
}

// UnimplementedFileInfoServer must be embedded to have forward compatible implementations.
type UnimplementedFileInfoServer struct {
}

func (UnimplementedFileInfoServer) GetFileInfo(context.Context, *FileReq) (*RegularFileInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileInfo not implemented")
}
func (UnimplementedFileInfoServer) GetDirFileInfo(context.Context, *FileReq) (*DirFileInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirFileInfo not implemented")
}
func (UnimplementedFileInfoServer) mustEmbedUnimplementedFileInfoServer() {}

// UnsafeFileInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileInfoServer will
// result in compilation errors.
type UnsafeFileInfoServer interface {
	mustEmbedUnimplementedFileInfoServer()
}

func RegisterFileInfoServer(s grpc.ServiceRegistrar, srv FileInfoServer) {
	s.RegisterService(&FileInfo_ServiceDesc, srv)
}

func _FileInfo_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileInfoServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FileInfo/GetFileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileInfoServer).GetFileInfo(ctx, req.(*FileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileInfo_GetDirFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileInfoServer).GetDirFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FileInfo/GetDirFileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileInfoServer).GetDirFileInfo(ctx, req.(*FileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FileInfo_ServiceDesc is the grpc.ServiceDesc for FileInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileInfo",
	HandlerType: (*FileInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileInfo",
			Handler:    _FileInfo_GetFileInfo_Handler,
		},
		{
			MethodName: "GetDirFileInfo",
			Handler:    _FileInfo_GetDirFileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fileInfo.proto",
}
